services:
  db:
    container_name: codejam-db
    image: postgres:17
    # ⚠️ Use only for direct debugging on the VPS database
    # ports:
    #   - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - database.env

  backend:
    image: codejam2025proton/backend:latest
    environment:
      - NODE_ENV=production
    env_file:
      - database.env
      - backend.env
    depends_on:
      db:
        condition: service_started

  code-execution:
    container_name: codejam-code-execution
    image: codejam2025proton/code-execution:latest
    volumes:
      # Use the host's docker daemon (DooD)
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - codeExecution.env

  frontend:
    image:
      codejam2025proton/frontend:latest
      # 👇 Override the default Docker file command (CMD) to serve the production build
    command: sh -c "npx serve -s dist -l 5173"
    environment:
      - GRAPHQL_SCHEMA_URL=http://backend:3000
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_started

  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx
      - ./logs:/var/log/nginx
    # 👇 Allow to pass a variable when running the docker compose command. Defaults to port host 8080 otherwise.
    ports:
      - ${GATEWAY_PORT:-8000}:80
    depends_on:
      - backend
      - frontend

volumes:
  dbdata:
    driver: local
