name: "Build and Push Docker Image"
description: "Common setup steps for building and pushing Docker images"
inputs:
  directory:
    description: "Name of the directory"
    required: true
  # docker-username:
  #   description: "Docker username"
  #   required: true
  # docker-token:
  #   description: "Docker personnal access token"
  #   required: true
  docker-repository:
    description: "Name of Dockerhub repository"
    required: true
runs:
  using: "composite"
  steps:
    # Enable multi-platform builds within Docker workflows by installing QEMU static binaries
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    # Create and boot a builder to be used in the following steps
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    # Log in to Docker Hub using personal access token
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # Build and push the properly tagged Docker image to Docker Hub using Buildx. By default, this actions use the Git context so there is no need to use the `actions/checkout` action to check out the repository as this will ne done directly by BuildKit.
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        context: "{{defaultContext}}:${{ inputs.directory }}"
        tags: ${{ inputs.docker-repository }}:${{ github.ref_name }}, ${{ inputs.docker-repository }}:latest
