name: ci

on:
  push:
    tags:
      - v*
    branch:
      - main
    if: "startsWith(github.ref, 'refs/tags/')"

jobs:
  build-frontend:
    # Run job only if:
    # - the commit is on the main branch
    # - the commit is tagged starting with v
    # if: ${{ github.ref == 'refs/heads/main' && startsWith(github.ref_name, 'v') }}
    runs-on: ubuntu-latest
    steps:
      # Enable multi-platform builds within Docker workflows by installing QEMU static binaries
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # Create and boot a builder to be used in the following steps
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Log in to Docker Hub using personal access token
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Debugging..."
        run: |
          echo "DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}"
          echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
          echo "DOCKER IMAGE NAME: ${{ vars.DOCKERHUB_USERNAME }}/frontend:${{ github.ref_name }}"
          echo "DOCKER IMAGE NAME V2: codejam/frontend:${{ github.ref_name }}"
      # Set up the default context for Buildx
      # Build and push the properly tagged Docker image to Docker Hub using Buildx. By default, this actions use the Git context so there is no need to use the `actions/checkout` action to check out the repository as this will ne done directly by BuildKit.
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:frontend"
          tags: codejam/frontend:${{ github.ref_name }}

  build-backend:
    runs-on: ubuntu-latest
    steps:
      # Enable multi-platform builds within Docker workflows by installing QEMU static binaries
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # Create and boot a builder to be used in the following steps
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Log in to Docker Hub using personal access token
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build and push the properly tagged Docker image to Docker Hub using Buildx. By default, this actions use the Git context so there is no need to use the `actions/checkout` action to check out the repository as this will ne done directly by BuildKit.
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:backend"
          tags: codejam/backend:${{ github.ref_name }}
