name: ci-build

on:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  build-frontend:
    # Run job only if:
    # - the commit is on the main branch
    # - the commit is tagged starting with v
    runs-on: ubuntu-latest
    if: startsWith(github.ref_name, 'v')
    steps:
      # Retrieve code from the repository (mandatory prior to using the custom local action)
      - name: Check out code
        uses: actions/checkout@v4
      # Custom action to login to Docker Hub, build and push the Docker image
      - uses: ./.github/actions/build-common-steps
        with:
          directory: 'frontend'
          docker-username: ${{ vars.DOCKERHUB_USERNAME }}
          docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
          docker-repository: ${{ vars.DOCKERHUB_REPO_FRONTEND }}

  build-backend:
    # Run job only if:
    # - the commit is on the main branch
    # - the commit is tagged starting with v
    runs-on: ubuntu-latest
    if: startsWith(github.ref_name, 'v')
    steps:
      # Retrieve code from the repository (mandatory prior to using the custom local action)
      - name: Check out code
        uses: actions/checkout@v4
      # Custom action to login to Docker Hub, build and push the Docker image
      - uses: ./.github/actions/build-common-steps
        with:
          directory: 'frontend'
          docker-username: ${{ vars.DOCKERHUB_USERNAME }}
          docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
          docker-repository: ${{ vars.DOCKERHUB_REPO_BACKEND }}
