name: ci

on:
  push:
    tags:
      - v*
    branch:
      - main
    if: "startsWith(github.ref, 'refs/tags/')"

jobs:
  build-frontend:
    # Run job only if:
    # - the commit is on the main branch
    # - the commit is tagged starting with v
    runs-on: ubuntu-latest
    steps:
      # Enable multi-platform builds within Docker workflows by installing QEMU static binaries
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # Create and boot a builder to be used in the following steps
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Log in to Docker Hub using personal access token
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Set up the default context for Buildx
      # Build and push the properly tagged Docker image to Docker Hub using Buildx. By default, this actions use the Git context so there is no need to use the `actions/checkout` action to check out the repository as this will ne done directly by BuildKit.
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:frontend"
          tags: ${{ vars.DOCKERHUB_REPO }}/frontend:${{ github.ref_name }}, ${{ vars.DOCKERHUB_REPO }}/frontend:latest
      # Output the image digest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-backend:
    runs-on: ubuntu-latest
    steps:
      # Enable multi-platform builds within Docker workflows by installing QEMU static binaries
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # Create and boot a builder to be used in the following steps
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Log in to Docker Hub using personal access token
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build and push the properly tagged Docker image to Docker Hub using Buildx. By default, this actions use the Git context so there is no need to use the `actions/checkout` action to check out the repository as this will ne done directly by BuildKit.
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:backend"
          tags: ${{ vars.DOCKERHUB_REPO }}/backend:${{ github.ref_name }}, ${{ vars.DOCKERHUB_REPO }}/backend:latest
      # Output the image digest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
