name: ci-release

# Run release job only after successful completion of the "ci" workflow
on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

permissions:
  contents: write # 👈 required for semantic-release to create tags and push commits

jobs:
  release:
    name: Release with semantic-release
    # Run release job only if the "ci" workflow completed successfully, and only if the commit is on the main branch
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      # Retrieve code from the repository (mandatory prior to using the custom local action)
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 👈 mandatory to access git history and retrieve existing tags

      # Setup Node.js environment on the CI runner
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install pnpm as package manager
      - name: Install pnpm
        shell: bash
        run: npm install -g pnpm@latest-10

      # Clean install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 👈 default GitHub token OR a GitHub personnal access token ("Tokens (classic)") with read/write permissions must first be created and add to the repo's actions secrets for semantic-release to be able to create tags and push commits
          GIT_AUTHOR_NAME: "github-actions[bot]"
          GIT_AUTHOR_EMAIL: "github-actions[bot]@users.noreply.github.com"
        run: npx semantic-release
