name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  # Job to run change detection: enable conditional execution of workflow steps and jobs, based on the files modified by pull request, on a feature branch, or by the recently pushed commits
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    # permissions:
    #   pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  test-frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      # Install pnpm as package manager
      - name: Install pnpm
        run: npm install -g pnpm@latest-10
      # Retrieve code from the repository
      - name: Check out code
        uses: actions/checkout@v4
      # Run frontend tests
      - name: Go to frontend and run tests
        run: cd frontend && pnpm install && pnpm run test

  test-backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      # Install pnpm as package manager
      - name: Install pnpm
        run: npm install -g pnpm@latest-10
      # Retrieve code from the repository
      - name: Check out code
        uses: actions/checkout@v4
      # Run frontend tests
      - name: Go to backend and run tests
        run: cd backend && pnpm install && pnpm run test:db
